#!/bin/sh
# SPDX-License-Identifier: BSD-2-Clause
set -e

# generate list of source files for use in Makefile.am
# if you add new source files, you must run ./bootstrap again
src_listvar () {
    basedir=$1
    suffix=$2
    var=$3

    find "${basedir}" -maxdepth 1 -name "${suffix}" | LC_ALL=C sort | tr '\n' ' ' | (printf "${var} = " && cat)
    echo ""
}

VARS_FILE=src_vars.mk
AUTORECONF=${AUTORECONF:-autoreconf}

echo "Generating file lists: ${VARS_FILE}"
(
  src_listvar "src" "*.c" "HDCR_C"
  src_listvar "src" "*.h" "HDCR_H"
  printf "HDCR_SRC = \$(LIB_PKCS11_C) \$(LIB_PKCS11_H)\n"

  src_listvar "src/lib" "*.c" "LIB_HDCR_C"
  src_listvar "src/lib" "*.h" "LIB_HDCR_H"
  printf "LIB_HDCR_SRC = \$(LIB_HDCR_C) \$(LIB_HDCR_H)\n"

  src_listvar "src/libdip" "*.c" "LIB_DIP_C"
  src_listvar "src/libdip" "*.h" "LIB_DIP_H"
  printf "LIB_DIP_SRC = \$(LIB_DIP_C) \$(LIB_DIP_H)\n"
) > ${VARS_FILE}

mkdir -p m4
${AUTORECONF} --install --sym $@
